# Generated by Django 2.2.2 on 2019-06-23 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('posted_time', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('project_details', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skills_required', models.TextField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
        ),
    ]
